### ISSUE TITLE
What is the recommended V2 API NodeJS Client

### ISSUE THREAD

**Issue by jmcombs** [dialogflow/dialogflow-nodejs-client#113]
I am currently utilizing the apiai NodeJS client for integration with Dialogflow. Since apiai utilizes the V1 API, what NodeJS client, similar to apiai, is recommended for use with the V2 API?

**Comment by arnm** [comment]
bump

**Comment by jmcombs** [comment]
The answer is [GitHub - nodejs-dialogflow](https://github.com/googleapis/nodejs-dialogflow)

**Comment by jmcombs** [comment]
The answer is [GitHub - nodejs-dialogflow](https://github.com/googleapis/nodejs-dialogflow)
