### ISSUE TITLE
simplest webhook to echo user entry

### ISSUE THREAD

**Issue by dougmaloney** [dialogflow/dialogflow-nodejs-client#45]
I'm really having problems firing a node.js webhook action from my api.ai bot. can anyone point me at the simplest possible example of a node webhook that just echoes the user entry so I can go from there ? appreciate it.

**Comment by rajnish-kumar-76** [comment]
Hi,
I am seeing this message really late. Have you achieved what you wanted to do. If not I can lend a hand.

Cheers,
-Rajnish

**Comment by dougmaloney** [comment]
no - figured it out - thanks anyway
