### ISSUE TITLE
Multilanguage support textRequest

### ISSUE THREAD

**Issue by MikeVerhees** [dialogflow/dialogflow-nodejs-client#95]
Hello,

so according to https://api.ai/docs/multi-language I can send the agent's language within the textRequest like so by providing the 'lang' parameter. However I've logged the result and the language is still set to 'en' even when I'm providing 'nl'

my textRequest looks like this:
`var request = app.textRequest(commandData.text,  {
        sessionId: `func${chatID}`
, lang: commandData.lang
    });`

I've checked the examples and it seems the language is set when defining apiai. So am I doing something wrong or does the nodeJS client just not support setting the language at the request itself?

Thanks!

**Comment by klemensz** [comment]
Same issue here. Have you found a solution?

**Comment by klemensz** [comment]
It seems that this works:
`var app = apiai('api_token_here', {language: 'nl'});`
So creating one app object with the same API token for each language should work.

**Comment by ppdeassis** [comment]
After some code diving, I'm using the following workaround, reusing the same `app`:
```javascript
const apiai = require('apiai')
const app = apiai('<your token here>', { version: '20170712' })  // ref below

// ...

// before every request, make sure to set the language property of app
app.language = '<your lang here>' // e.g. 'pt-BR', 'en-US', 'es-ES', ...
app.textRequest(text, { sessionId })

// ...
```

----
_ref: [`version: '20170712'`](https://dialogflow.com/docs/reference/agent/#protocol_version) - uses `@sys.number` as numbers instead of strings_

**Comment by nvtuan305** [comment]
I have the same issue. Have you found a solution?

@ppdeassis I have try your solution but it's not working

**Comment by ppdeassis** [comment]
@nvtuan305 I've updated the _code sample_ above, providing more details.

**Comment by nvtuan305** [comment]
@ppdeassis Thank you! It's working. Another working solution is:
```
const aiClient = apiai('dialog_flow_access_token', { language: 'ja' });
aiClient.send(<parameters>);

// To change language
aiClient.language('en');
```

**NOTE**: If you pass a invalid language [(supported languages),](https://dialogflow.com/docs/reference/language) the Dialogflow (apiai) will use the default language of the agent.
